name: Deploying Resume Website

on:
    push:
        branches:
            - main
    
            
          
permissions:
    contents: read
    id-token: write
    

jobs:
    terraform:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: terraform
        


        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.5.0

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-to-assume: arn:aws:iam::604312263409:role/githubuser
                aws-region: us-east-1

            - name: Create s3 bucket for Terraform state
              run: |
                aws s3api create-bucket --bucket resume-website-terraform-state-16-08-2024 --region us-east-1
            - name: Initialize _Terraform
              run: terraform init 

          
    
            - name: Terraform Validate
              run: terraform validate

            - name: Terraform  Plan
              run: terraform plan


            - name: Terraform Apply              
              run: terraform apply -auto-approve

            - name: Sync files to S3
              run: |
                if aws s3api head-bucket --bucket kwabena-resume-website-25-10-2025 2>/dev/null; then
                    echo "Bucket exists, syncing website..."
                    aws s3 sync ../website s3://kwabena-resume-website-25-10-2025/ --delete --region us-east-1
                else
                    echo "Bucket does not exist, skipping sync."
                fi
