name: Deploying-Resume-Website

on:
    push:
        branches:
            - main
permissions:
    contents: read
    id-token: write
    

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: 1.5.0

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-to-assume: arn:aws:iam::914559461558:role/GithubActions
                aws-region: us-east-1

            - name: Create s3 bucket for Terraform state
              run: |
                aws s3api create-bucket --bucket resume-website-terraform-state-16-08-2024 --region us-east-1
            - name: Initialize _Terraform
              run: terraform -chdir=terraform init -migrate-state

            - name: Terraform Validate
              run: terraform -chdir=terraform validate

            - name: Terraform Plan
              run: terraform -chdir=terraform plan

            - name: Terraform destroy
              run: terraform -chdir=terraform destroy -auto-approve || true

            - name: Terraform Apply
              run: terraform -chdir=terraform apply -auto-approve

            - name: Sync files to S3
              run: |
                aws s3 sync ./website s3://kwabena-resume-website-15-08-2024/ --delete